### PR TITLE
rewrite unit tests

### PR DESCRIPTION
**Pull request by salsa-dev**
WIP #25

### CODE REVIEW

**Comment by salsa-dev** [comment]
Something like that. Still in WIP to polish.
I'm on:
```
serge@home:~/DEV/netdata-cookbook$ chef -v
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13

```

**Comment by salsa-dev** [comment]
@jmadureira , @nictrix  Your suggestions or any remarks ?

**Comment by nictrix** [comment]
I like it, looks good 👍

**Comment by salsa-dev** [comment]
@jmadureira which version of chef Travis is using ?
I do have everything clean:
```
Finished in 4.54 seconds (files took 1.47 seconds to load)
68 examples, 0 failures

Randomized with seed 50959


ChefSpec Coverage report generated...

  Total Resources:   37
  Touched Resources: 37
  Touch Coverage:    100.0%

```

**Comment by jmadureira** [comment]
@salsa-dev it is supposed to be using chef 12.9.38.

**Comment by salsa-dev** [comment]
@jmadureira I replaced `nothing` actions with `do_nothing` that caused errors (due to chef version) and replaced all `let` with `cached` to speed up execution. Now some errors appear that I am not sure I can handle. Could you have a look, please?

**Comment by jmadureira** [comment]
@salsa-dev I'll have a look. Just discovered that tests fails on chef 13.8.0 so I'll may have to start by looking into matrix builds on travis to see why this is happening.

On a sidenote the problem reported on #22 may be related with the way attributes get merged within the root context that somehow is solved when using the compat_resources cookbook. I'll take a look at that as well.

**Comment by salsa-dev** [comment]
@jmadureira I'm testing compat_resource dependency now. It seems to work only from chef 12.6.0. I will create separate issue and PR for this right now.

**Comment by salsa-dev** [comment]
PR is ready

**Pull request merged**
