### PR TITLE
adding new_resource designation for chef 13+ compatibility

### PR DESCRIPTION
**Pull request by bobchaos**

### CODE REVIEW

**Comment by bobchaos** [comment]
patch version bump may be in order, leaving to your discretion

**Comment by st-h** [comment]
Just have been running into this issue and I can confirm that this fixes compatibility with chef 14.1.

**Comment by bobchaos** [comment]
patch version bumped, ready for merge!

**Comment by bobchaos** [comment]
I see you're working on a major refactor, any chance this will get published to the supermarket before the next big release? Life is always better when you can let berkshelf handle your external cookbooks :D

**Comment by jmadureira** [comment]
Just published v0.4.1 with your fix. If you find any issue let me know.

**Pull request merged**
